### ISSUE TITLE
btw

### ISSUE THREAD

**Issue by JustSpaceisded** [om3ga6400/om3ga6400-old#1]
btw the last time i forked one your things you said fork it and use it and you kept saying new update refork then you say stop forking so ill stop forking

**Comment by JustSpaceisded** [comment]
ALSO OMEGA STFU YOU UGLY PEACE OF SHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIT.

**Comment by om3ga6400** [comment]
monky
