### ISSUE TITLE
your yt no work

### ISSUE THREAD

**Issue by JustSpaceisded** [om3ga6400/om3ga6400-old#3]
for the yt you did https://www.youtube.com/omega_gd but your suppost to do an @omega_gd like this

https://www.youtube.com/@omega_gd fix it

**Comment by JustSpaceisded** [comment]
@OMEGA6405

**Comment by om3ga6400** [comment]
What yt link I have quite a few

**Comment by om3ga6400** [comment]
Oh, I see it nvm

**Comment by JustSpaceisded** [comment]
> Oh, I see it nvm

ok cool

**Comment by om3ga6400** [comment]
@Progamer1251718 naex time make a pull requet
